services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: api_places
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  api:
    build: .
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      GOOGLE_PLACES_API_KEY: ${GOOGLE_PLACES_API_KEY}
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: api_places
      DB_USER: postgres
      DB_PASSWORD: postgres
    depends_on:
      - db

volumes:
  postgres_data:
